<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="582" started-at="2018-04-26T06:08:44Z" finished-at="2018-04-26T06:08:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="582" started-at="2018-04-26T06:08:44Z" finished-at="2018-04-26T06:08:45Z">
      <class name="com.maventest.mavens.ExtentManager">
        <test-method status="PASS" signature="startTest()[pri:0, instance:com.maventest.mavens.ExtentManager@14bf9759]" name="startTest" is-config="true" duration-ms="270" started-at="2018-04-26T11:38:44Z" finished-at="2018-04-26T11:38:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="FAIL" signature="demoReportFail()[pri:0, instance:com.maventest.mavens.ExtentManager@14bf9759]" name="demoReportFail" duration-ms="9" started-at="2018-04-26T11:38:45Z" finished-at="2018-04-26T11:38:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[test Failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: test Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.maventest.mavens.ExtentManager.demoReportFail(ExtentManager.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportFail -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.maventest.mavens.ExtentManager@14bf9759]" name="getResult" is-config="true" duration-ms="7" started-at="2018-04-26T11:38:45Z" finished-at="2018-04-26T11:38:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportFail status=FAILURE method=ExtentManager.demoReportFail()[pri:0, instance:com.maventest.mavens.ExtentManager@14bf9759] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="demoReportPass()[pri:0, instance:com.maventest.mavens.ExtentManager@14bf9759]" name="demoReportPass" duration-ms="2" started-at="2018-04-26T11:38:45Z" finished-at="2018-04-26T11:38:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportPass -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.maventest.mavens.ExtentManager@14bf9759]" name="getResult" is-config="true" duration-ms="0" started-at="2018-04-26T11:38:45Z" finished-at="2018-04-26T11:38:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportPass status=SUCCESS method=ExtentManager.demoReportPass()[pri:0, instance:com.maventest.mavens.ExtentManager@14bf9759] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.maventest.mavens.ExtentManager@14bf9759]" name="endReport" is-config="true" duration-ms="263" started-at="2018-04-26T11:38:45Z" finished-at="2018-04-26T11:38:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.maventest.mavens.ExtentManager -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
